### ISSUE TITLE
Order of width and height

### ISSUE THREAD

**Issue by ZoeBijl** [postcss/postcss-size#3]
Most css properties follow the vertical followed by horizontal pattern, like padding, margin, and border-width. Should this follow that logic? Also see this proposal: http://discourse.wicg.io/t/shorthand-for-width-height-css-longhands/1160

**Comment by ai** [comment]
CSS is very unconsistence here. For example: `background-size: [width] [height]`.

Anyway this changes will broke all old code, so new plugin is a better way.
