### ISSUE TITLE
Add support for max-* and min-*

### ISSUE THREAD

**Issue by askoretskiy** [postcss/postcss-size#8]
It would be great if that plugin supports min-width/min-height and max-width/max-height.

I.e. min-size => min-width + min-height ; max-size => max-width + max-height

I suppose that would be a trivial change but rather handy improvement.

**Comment by ai** [comment]
Nice idea. Please send PR.

**Comment by Airkro** [comment]
[postcss-short-size](https://github.com/jonathantneal/postcss-short-size) already do that

**Comment by ai** [comment]
I'm. Maybe I should deprecate this plugin?

**Comment by Airkro** [comment]
@ai
I don't know, but i like this plugin too, It's simple for beginner like me

i have forking it to make a [new plugin](https://github.com/Airkro/postcss-overflow) for my project, thanks

**Comment by ai** [comment]
@Airkro wow, nice plugin, you should add it to postcss-short.

**Comment by ai** [comment]
I close this issue, because it is already done in postcss-short-size

**Comment by meduzen** [comment]
Hi @ai! As `postcss-short-size` is not maintained anymore, I think this issue can be re-open.

**Comment by meduzen** [comment]
PR incoming!

**Comment by ai** [comment]
The support was released in 5.0.
